# ~/.tmuxinator/dev.yml

name: dev
root: ~/

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Project hooks
# Runs on project start, always
# on_project_start: command
# Run on project start, the first time
# on_project_first_start: command
# Run on project start, after the first time
# on_project_restart: command
# Run on project exit ( detaching from tmux session )
# on_project_exit: command
# Run on project stop
# on_project_stop: command

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
startup_pane: 1

windows:
  - dev:
      layout: even-vertical
      root: ~/src/market/gmarket
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - npm run watch:dev
        -
  - srv:
      root: ~/src/market/docker
      panes:
        - tmux move-window -d -s 1 -t 98; make run
  - ♪:
      layout: 8bfc,86x55,0,0[86x42,0,0,2,86x12,0,43,11]
      root: ~/etc/music
      panes:
        - tmux move-window -d -s 2 -t 99; cmus
        - cava
